### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [boldtrn/graphhopper-maps-capacitor#26]
I've tried a quick fix ( https://gitlab.com/fdroid/fdroiddata/-/commit/4ca2e30af20e173862ce4d24e0dee449834f37cc )  but more changes are needed: https://gitlab.com/fdroid/fdroiddata/-/jobs/3761808665#L368

/LE: https://gitlab.com/fdroid/fdroiddata/-/commit/4ca2e30af20e173862ce4d24e0dee449834f37cc

**Comment by boldtrn** [comment]
Thanks a lot for looking into this @licaon-kter 👍.

I created a [MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12607) at f-droid. I hope this resolves the issue.
