### ISSUE TITLE
When planning a route for a vehicle, take into road traffic

### ISSUE THREAD

**Issue by Korb** [boldtrn/graphhopper-maps-capacitor#37]
You can read more about the intricacies of using global and local traffic data providers in the discussion "[Integrate Traffic Data from different sources (e.g. from the German bundes API)](https://github.com/organicmaps/organicmaps/issues/1160)" of the Organic Maps project.

**Comment by boldtrn** [comment]
Thanks for opening issues here. You might want to see if these can be integrated in the graphhopper-maps repository as this app is only a wrapper for that. https://github.com/graphhopper/graphhopper-maps

**Comment by Korb** [comment]
@boldtrn, is this project on Github correctly listed as the main project for [the GraphHopper Maps app on F-Droid](https://f-droid.org/packages/com.graphhopper.maps/)?

**Comment by boldtrn** [comment]
It is, when you look at the code you will see what I mean.
